name: LagUtils
version: '${project.version}'
main: org.nixtils.lagutils.LagDetector
api-version: '1.20'
authors: [Nix]
description: A simple plugin to detect large clumps of armor stands and other laggy entities.
commands:
  lagutils:
    permission: lagutils.command
    permission-message: "&7[&bLagUtils&7] &cYou don't have permission to use this command!"
    description: Main command of the LagUtilities plugin.
